version: 2

models:
  - name: stg_machines
    columns:
      - name: machine_id
        tests: [not_null, unique]
      - name: line_id
        tests: [not_null]
  - name: stg_sensor_readings
    columns:
      - name: machine_id
        tests:
          - not_null
          - relationships:
              arguments:
                to: ref('stg_machines')
                field: machine_id
      - name: shift
        tests:
          - accepted_values:
              arguments:
                values: ['Night', 'Day', 'Evening']
  - name: stg_quality_checks
    columns:
      - name: quality_check_id
        tests: [not_null, unique]
      - name: defect_type
        tests:
          - not_null
          - accepted_values:
              arguments:
                values: ['Assembly', 'Dimensional', 'Electrical', 'No Defect', 'Surface']
  - name: stg_downtime_events
    columns:
      - name: downtime_event_id
        tests: [not_null, unique]
  - name: stg_maintenance_logs
    columns:
      - name: maintenance_id
        tests: [not_null, unique]
  - name: stg_production_batches
    columns:
      - name: batch_id
        tests: [not_null, unique]
      - name: shift
        tests:
          - accepted_values:
              arguments:
                values: ['Night', 'Day', 'Evening']
