name: "dbt_mfg"
version: "1.0.0"
config-version: 2

profile: "dbt_mfg"

model-paths: ["models"]
target-path: "target"
clean-targets: ["target", "dbt_packages"]

models:
  dbt_mfg:
    staging:
      +materialized: view
    intermediate:
      +materialized: table
    marts:
      +materialized: table
