version: 2

models:
  - name: int_machine_hourly_metrics
    columns:
      - name: machine_id
        tests: [not_null]
      - name: metric_hour
        tests: [not_null]
  - name: int_batch_quality_features
    columns:
      - name: batch_id
        tests: [not_null]
  - name: int_machine_daily_health
    columns:
      - name: machine_id
        tests: [not_null]
      - name: metric_day
        tests: [not_null]
  - name: int_downtime_features
    columns:
      - name: machine_id
        tests: [not_null]
      - name: metric_day
        tests: [not_null]
